COUNTRIES = [
    {
        "code": "tr",
        "name": "Турция",
        "name_en": "Turkey",
        "description": "Страна на стыке Европы и Азии. Идеальна для пляжного отдыха.",
        "description_en": "A country bridging Europe and Asia. Perfect for a beach holiday.",
        "image": "images/turkey.jpg",
        "price": 45000,
    },
    {
        "code": "it",
        "name": "Италия",
        "name_en": "Italy",
        "description": "Колыбель Ренессанса, римские руины и лучшая паста.",
        "description_en": "The cradle of the Renaissance, Roman ruins and the best pasta.",
        "image": "images/italy.jpg",
        "price": 78000,
    },
    {
        "code": "jp",
        "name": "Япония",
        "name_en": "Japan",
        "description": "Страна восходящего солнца: сакура, технологии и традиции.",
        "description_en": "Land of the rising sun: sakura, technology and tradition.",
        "image": "images/japan.jpg",
        "price": 120000,
    },
    {
        "code": "eg",
        "name": "Египет",
        "name_en": "Egypt",
        "description": "Пирамиды, Красное море и древняя история.",
        "description_en": "Pyramids, the Red Sea and ancient history.",
        "image": "images/egypt.jpg",
        "price": 55000,
    },
]

TRANSPORT_CHOICES = [
    ("plane", "Самолёт"),
    ("train", "Поезд"),
    ("car", "Автомобиль"),
    ("bus", "Автобус"),
]

LANGUAGES = [
    ("ru", "Русский"),
    ("en", "English"),
]

THEMES = [
    ("light", "Светлая"),
    ("dark", "Тёмная"),
]

TRANSLATIONS = {
    "ru": {
        "title": "Планировщик путешествий",
        "subtitle": "Спланируйте свою идеальную поездку",
        "form_title": "Новое путешествие",
        "name_label": "Ваше имя",
        "country_label": "Страна",
        "date_label": "Дата поездки",
        "days_label": "Количество дней",
        "transport_label": "Транспорт",
        "budget_label": "Бюджет, ₽",
        "notes_label": "Заметки",
        "save_btn": "Сохранить",
        "settings_title": "Настройки",
        "theme_label": "Тема",
        "language_label": "Язык",
        "save_settings": "Применить",
        "last_visit": "Последний визит",
        "countries_title": "Популярные направления",
        "success": "Путешествие сохранено!",
        "from_price": "от",

        "trips_title": "Мои путешествия",
        "trips_empty": "Пока нет сохранённых путешествий. Заполните форму выше.",
        "trips_count": "Всего поездок",
        "delete_btn": "Удалить",
        "clear_btn": "Очистить всё",
        "created_label": "Создано",
        "days_short": "дн.",
        "budget_short": "Бюджет",
        "notes_short": "Заметки",
        "confirm_clear": "Удалить все сохранённые поездки?",
        "confirm_delete": "Удалить эту поездку?",
    },
    "en": {
        "title": "Travel Planner",
        "subtitle": "Plan your perfect trip",
        "form_title": "New Trip",
        "name_label": "Your name",
        "country_label": "Country",
        "date_label": "Travel date",
        "days_label": "Number of days",
        "transport_label": "Transport",
        "budget_label": "Budget, ₽",
        "notes_label": "Notes",
        "save_btn": "Save",
        "settings_title": "Settings",
        "theme_label": "Theme",
        "language_label": "Language",
        "save_settings": "Apply",
        "last_visit": "Last visit",
        "countries_title": "Popular destinations",
        "success": "Trip saved!",
        "from_price": "from",

        "trips_title": "My Trips",
        "trips_empty": "No saved trips yet. Fill the form above.",
        "trips_count": "Total trips",
        "delete_btn": "Delete",
        "clear_btn": "Clear all",
        "created_label": "Created",
        "days_short": "days",
        "budget_short": "Budget",
        "notes_short": "Notes",
        "confirm_clear": "Delete all saved trips?",
        "confirm_delete": "Delete this trip?",
    },
}
